/**
 * Sample React Native App
 *
 * Generated by Nguyen Phuc Bao Chau
 * https://github.com/chaudev/react-native-base
 *
 * https://ischau.org
 *
 */

import React, {useEffect} from 'react'
import {LogBox, Platform, StatusBar, View} from 'react-native'
import {SafeAreaProvider} from 'react-native-safe-area-context'
import OneSignal from 'react-native-onesignal'
import RootNavigator from '~/navigators/root'
import AppProvider from '~/provider/AppProvider'

LogBox.ignoreAllLogs()

const App = () => {
  async function initOneSignal() {
    // OneSignal Initialization
    OneSignal.setAppId('939f0293-b2f9-4eed-92b6-4bdb8e7a7a06')

    // requestPermission will show the native iOS or Android notification permission prompt.
    // We recommend removing the following code and instead using an In-App Message to prompt for notification permission
    if (Platform.OS === 'ios') {
      OneSignal.promptForPushNotificationsWithUserResponse(response => {
        console.log('App - Prompt response:', response)
      })
    }

    const deviceState = await OneSignal.getDeviceState()

    console.log('--- deviceState: ', deviceState)

    OneSignal.setNotificationWillShowInForegroundHandler(notificationReceivedEvent => {
      let notification = notificationReceivedEvent.getNotification()
      console.log('notification: ', notification)
      const data = notification.additionalData
      console.log('additionalData: ', data)
    })

    OneSignal.setNotificationOpenedHandler(notification => {
      console.log('notification:', notification)
    })
  }

  useEffect(() => {
    initOneSignal()
  }, [])

  return (
    <View style={{flex: 1}}>
      <StatusBar translucent={true} backgroundColor="rgba(0,0,0,0)" />
      <SafeAreaProvider>
        <AppProvider>
          <RootNavigator />
        </AppProvider>
      </SafeAreaProvider>
    </View>
  )
}

export default App
